variable "colab_project_id" {
  description = "Shared project that owns Colab Enterprise runtime templates/runtimes"
  type        = string
}

variable "target_project_id" {
  description = "Project that owns the task BigQuery dataset, GCS workspace and task service account"
  type        = string
}

variable "network_project_id" {
  description = "Project that owns the VPC/subnet. Use Shared VPC host project when applicable."
  type        = string
}

variable "network_name" {
  description = "Existing VPC name for Colab runtimes"
  type        = string
}

variable "subnetwork_name" {
  description = "Existing subnet name for Colab runtimes"
  type        = string
}

variable "colab_location" {
  description = "Colab Enterprise region"
  type        = string
  default     = "asia-northeast3"
}

variable "task_id" {
  description = "Approved data-model task ID"
  type        = string
}

variable "task_name" {
  description = "Approved data-model task name"
  type        = string
}

variable "group" {
  description = "Task group/domain code"
  type        = string
  default     = "analysis"
}

variable "request_user" {
  description = "Primary approved corporate Google identity"
  type        = string
}

variable "team_users_csv" {
  description = "Additional approved users as comma-separated email addresses"
  type        = string
  default     = ""
}

variable "dataset_id" {
  description = "BigQuery dataset ID generated by the adapter"
  type        = string
}

variable "bq_location" {
  description = "BigQuery dataset location"
  type        = string
  default     = "asia-northeast3"
}

variable "bigquery_role" {
  description = "Dataset role granted to approved users"
  type        = string
  default     = "editor"

  validation {
    condition     = contains(["viewer", "editor", "owner"], lower(var.bigquery_role))
    error_message = "bigquery_role must be viewer, editor, or owner."
  }
}

variable "machine_type" {
  description = "Compute Engine machine type used by each Colab runtime"
  type        = string
  default     = "e2-standard-4"
}

variable "accelerator_type" {
  description = "Optional accelerator type such as NVIDIA_TESLA_T4. Empty means CPU only."
  type        = string
  default     = ""
}

variable "accelerator_count" {
  description = "Accelerator count when accelerator_type is set"
  type        = number
  default     = 0

  validation {
    condition     = var.accelerator_count >= 0
    error_message = "accelerator_count must be zero or greater."
  }
}

variable "disk_type" {
  description = "Persistent data disk type for each Colab runtime"
  type        = string
  default     = "pd-balanced"
}

variable "disk_size_gb" {
  description = "Persistent data disk size per runtime"
  type        = number
  default     = 100

  validation {
    condition     = var.disk_size_gb >= 10 && var.disk_size_gb <= 65536
    error_message = "disk_size_gb must be between 10 and 65536 GB."
  }
}

variable "idle_shutdown_minutes" {
  description = "Idle timeout before Colab stops runtime compute. 0 disables idle shutdown."
  type        = number
  default     = 60

  validation {
    condition = (
      var.idle_shutdown_minutes == 0 ||
      (var.idle_shutdown_minutes >= 10 && var.idle_shutdown_minutes <= 1440)
    )
    error_message = "idle_shutdown_minutes must be 0, or between 10 and 1440 minutes."
  }
}

variable "enable_internet_access" {
  description = "Whether Colab runtime receives public internet access"
  type        = bool
  default     = false
}

variable "enable_end_user_credentials" {
  description = "Use the runtime user's identity for interactive Google Cloud API access"
  type        = bool
  default     = true
}

variable "runtime_desired_state" {
  description = "Initial runtime state. STOPPED minimizes compute cost until use."
  type        = string
  default     = "STOPPED"

  validation {
    condition     = contains(["RUNNING", "STOPPED"], upper(var.runtime_desired_state))
    error_message = "runtime_desired_state must be RUNNING or STOPPED."
  }
}

variable "colab_release_name" {
  description = "Colab image release name"
  type        = string
  default     = "py312"
}

variable "startup_script_url" {
  description = "Optional gs:// or https:// post-startup script used to install corporate packages/configuration"
  type        = string
  default     = ""

  validation {
    condition = (
      var.startup_script_url == "" ||
      startswith(var.startup_script_url, "gs://") ||
      startswith(var.startup_script_url, "https://")
    )
    error_message = "startup_script_url must be empty, gs://..., or https://...."
  }
}

variable "storage_location" {
  description = "GCS workspace bucket location"
  type        = string
  default     = "asia-northeast3"
}

variable "allow_destroy_data" {
  description = "Allow Terraform to delete non-empty BigQuery/GCS task data on destroy"
  type        = bool
  default     = false
}

variable "kms_key_name" {
  description = "Optional full CMEK key resource name for Colab runtime persistent storage"
  type        = string
  default     = ""
}

variable "expire_date" {
  description = "Business lifecycle metadata, YYYY-MM-DD"
  type        = string
  default     = ""
}
